name: Develop Deploy

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Digital Ocean
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: bash pfk-app/deploy.sh
          username: root
          host: ${{ secrets.HOST_DEVELOP }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
